services:
  postgres:
    image: postgres:14.24-alpine3.23
    environment:
      POSTGRES_PASSWORD: $DBPASS
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBDB
    volumes:
      - postgresapi:/var/lib/postgresql/data
    restart: always
  api-fastapi:
    image: ghcr.io/aelxdc/devops-lab/api-fastapi:1.3
    environment:
      DATABASE_URL: $DBURL
    ports:
      - 8000:8000
    restart: always
    depends_on: 
      - postgres
volumes:
  postgresapi:
